girl:
     cupSize: B
     age: 18
spring:
  profiles:
    active: dev
  datasource:
    name: mysql_dev
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
          #监控统计拦截的filters
          filters: stat
          url: jdbc:mysql://127.0.0.1:3306/2019?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
#          url: jdbc:mysql://123.206.91.106:3306/201807031?useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: root
#          password: 123456
          password:

      #          password: lijiahangA1$
          initial-size: 1
          min-idle: 1
          max-active: 20
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
          ## jackson是设置全局时区和格式(不如在sql中直接上)
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #设置方言解决无外键问题
  security:
    user:
      name: jiahanglee
      password: 123456

mybatis:
  mapper-locations: classpath:mapper/PrivilegeDao.xml
  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.winter.demo.entity  # 注意：对应实体类的路径

#server:
#  servlet:
#    context-path: /babyship
## 该配置节点为独立的节点，有很多REN将这个配置放在spring的节点下，导致配置无法被识别
#mybatis:
#  mapper-locations: classpath:mapper/TeacherDao.xml ,classpath:mapper/NewsDao.xml ,classpath:mapper/UserDao.xml,classpath:mapper/RoleDao.xml,classpath:mapper/PrivilegeDao.xml,classpath:mapper/MenuDao.xml,classpath:mapper/PrivilegeDao.xml,classpath:mapper/MenuDao.xml,classpath:mapper/PrivilegeMenuDao.xml,classpath:mapper/RolePrivilegeDao.xml,classpath:mapper/UserRoleDao.xml,classpath:mapper/IssuesDao.xml
#  #注意：一定要对应mapper映射xml文件的所在路径
#
#  type-aliases-package: com.winter.entity  # 注意：对应实体类的路径

#pagehelper
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql
#    returnPageInfo: check

